function proiect(A1,A2,f,N,R1,R2,R3,R4);

Fig = figure('Name','Circuit diferential cu AO',...
             'Units','normalized',...
             'NumberTitle','off',...
             'Position',[0.2 0.2 0.7 0.8],...
             'Color', [0.5 0.5 0.9]);
T = 1/f;
t = 0:T/100:N*T;
vi1 = A1*sin(2*pi*f*t);
vi2 = A2*sin(2*pi*f*t);
nt=length(t);
if (A1 > A2)
vo = R2/R1*(A1-A2)*sin(2*pi*f*t);

else
   vo = R2/R1*(A2-A1)*sin(2*pi*f*t);
end


uicontrol('Style','pushbutton',...
          'Units','normalized',...
          'Position',[0.05 0.55 0.05 0.05],...
          'string','Calcul',...
          'Callback','close;proiect(A1,A2,f,N,R1,R2,R3,R4);');

uicontrol('Style','pushbutton',...
          'Units','normalized',...
          'Position',[0.05 0.45 0.1 0.05],...
          'string','Documentatie',...
          'Callback','open_doc();');

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.15 0.58 0.08 0.05],...
          'backgroundcolor',[0.5 0.5 0.9],...
          'string','A1');

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.15 0.55 0.08 0.05],...
          'String','A1',...
          'Callback',['A1=','str2num(get(gco,''String''))']);


uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.65 0.58 0.08 0.05],...
          'backgroundcolor',[0.5 0.5 0.9],...
          'string','A2');

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.65 0.55 0.08 0.05],...
          'String','A2',...
          'Callback',['A2=','str2num(get(gco,''String''))']);

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.465 0.48 0.05 0.05],...
          'backgroundcolor',[0.5 0.5 0.9],...
          'string','f');

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.465 0.45 0.05 0.05],...
          'String','f',...
          'Callback',['f=','str2num(get(gco,''String''))']);

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.45 0.88 0.08 0.05],...
          'backgroundcolor',[0.5 0.5 0.9],...
          'string','R1');

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.465 0.85 0.05 0.05],...
          'String','R1',...
          'Callback',['R1=','str2num(get(gco,''String''))']);

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.465 0.78 0.05 0.05],...
          'backgroundcolor',[0.5 0.5 0.9],...
          'string','`R2');

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.465 0.75 0.05 0.05],...
          'String','R2',...
          'Callback',['R2=','str2num(get(gco,''String''))']);

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.45 0.68 0.08 0.05],...
          'backgroundcolor',[0.5 0.5 0.9],...
          'string','R3');

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.465 0.65 0.05 0.05],...
          'String','R3',...
          'Callback',['R3=','str2num(get(gco,''String''))']);

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.45 0.58 0.08 0.05],...
          'backgroundcolor',[0.5 0.5 0.9],...
          'string','R4');

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.465 0.55 0.05 0.05],...
          'String','R4',...
          'Callback',['R4=','str2num(get(gco,''String''))']);

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.465 0.38 0.05 0.05],...
          'backgroundcolor',[0.5 0.5 0.9],...
          'string','N');

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.465 0.35 0.05 0.05],...
          'String','N',...
          'Callback',['N=','str2num(get(gco,''String''))']);

img = imread('circ_dif.png');
image(img);
set(gca,...
    'units',...
    'normalized',...
    'position',[0.05 0.69 0.4 0.25]);


subplot('position',[0.55 0.69 0.4 0.25]);
plot(t,vo);
grid on;
title('Vo');
xlabel('timp [s]');
ylabel('Amplitudine [V]');
subplot('position', [0.55 0.05 0.4 0.25]);
plot(t,vi2);
grid on;
title('Vi2');
xlabel('timp [s]');
ylabel('Amplitudine [V]');
subplot('position', [0.05 0.05 0.4 0.25]);
plot(t,vi1);
grid on;
title('Vi1');
xlabel('timp [s]');
ylabel('Amplitudine [V]');